### ISSUE TITLE
Unfreezing fn when AOT

### ISSUE THREAD

**Issue by etherny** [ptaoussanis/nippy#61]
When i compile my code in AOT mode, i can't freeze data if i use fn as hashmap value.
If i remove AOT compilation. all work fine.

**Comment by ptaoussanis** [comment]
Hi there, I'm afraid that's to be expected: Clojure `fn`s aren't the easiest thing to serialize (for one - they may involve closures, etc.). They *do* implement Java's Serializable interface (which is why Nippy is successfully freezing/thawing them at all) - but that tends to be error prone (e.g. across JVMs) and will definitely fail with AOT afaik.

Only real solution is to avoid needing to serialize a whole fn, unfortunately.

Sorry I couldn't offer anything more helpful!
