### ISSUE TITLE
nippy uses old version of timbre

### ISSUE THREAD

**Issue by lvh** [ptaoussanis/nippy#62]
Nippy depends on an old version of timbre. [This broke my build, because there's conflicting dependencies on encore](https://travis-ci.org/lvh/icecap/jobs/50905060). I think it would be fine to just upgrade the dependency, since I don't think there's any breaking API change. Right now, I've done it with just an exclusion, and that seems to work fine.

I don't know if [hatnik](http://hatnik.com) is a tool you know of/like, but FWIW, this is what automatically notified me of the latest version existing.

Thanks a lot for all of your work on nippy/timbre/etc! I'm a big fan of all of your projects :)

**Comment by ptaoussanis** [comment]
Hi there,

> I think it would be fine to just upgrade the dependency, since I don't think there's any breaking API change.

Absolutely, you can always use a newer Encore dependency. I'm busy migrating all Encore-lib consumers to a new design that'll print instructions on dep conflicts. Nippy hasn't been updated yet, but you can find the instructions [here](https://github.com/ptaoussanis/encore/blob/master/DEP-CONFLICT.md).

These contortions are unfortunately necessary since there's currently no reliable way to instruct Leiningen to just prefer newer versions of a lib.

> I don't know if hatnik is a tool you know of/like, but FWIW, this is what automatically notified me of the latest version existing.

I wasn't; I normally use [lein-ancient](https://github.com/xsc/lein-ancient) myself, though hatnik looks interesting - will check it out.

> Thanks a lot for all of your work on nippy/timbre/etc! I'm a big fan of all of your projects :)

You're very welcome, thanks for saying so.

Cheers! :-)
