### ISSUE TITLE
Is this clojurescript compatible?

### ISSUE THREAD

**Issue by yatesco** [ptaoussanis/nippy#64]
Title says it all :).

Thanks!

**Comment by mpenet** [comment]
It isn't, it relies heavily on external java libraries (ex. for compression), and jvm apis internaly.

**Comment by yatesco** [comment]
OK - thanks Max. Anyone fancy porting the JVM to ClojureScript - now that
would be a fun weekend ;).

**Comment by mpenet** [comment]
I think [transit](https://github.com/cognitect/transit-cljs) might be a good candidate for cljs, if you need something available now.

**Comment by yatesco** [comment]
Yeah, that is what I am using. Combined with edn and sente it is a
pleasure. However, I am now looking at persisting strings to and from the
database and came across this. The performance graph shocked me and the
lightweight protocol required to serialise protocols hence my consideration
for replacing edn.

I expect I will still use this to/from the database but retain edn for
clojure->clojurescript.

**Comment by ptaoussanis** [comment]
Hi Colin,

Unfortunately @mpenet is correct (thanks Max!). Transit & edn are your best options right now. Edn's better for small payloads, Transit for larger ones. And both may be amenable to string compression, but that'll depend largely on the size+kind of data you're dealing with.

Note that Transit theoretically has support for binary (MessagePack) encoding. Last I checked, it wasn't working (done?) - not sure if that's changed yet.

Hope that helps! Please feel free to close if you've got no further questions.

Cheers :-)

**Comment by yatesco** [comment]
Thanks all.

**Comment by ptaoussanis** [comment]
Since this question came up again, I'll just add here for the record that ClojureScript compatibility is specifically a non-goal for Nippy. 

Core motivation for the lib was+is to get something as fast+small as possible for server-side de/serialization (for use with a db, to disk, etc.). Unfortunately a focus on speed+size is (at least in this case) intrinsically in direct opposition to portability.

More or less:
- Edn maximises portability
- Nippy maximises performance/efficiency
- Transit strikes a balance between the two (/ arguably replaces edn)

Hope that helps!
