### ISSUE TITLE
provide specification

### ISSUE THREAD

**Issue by mpenet** [ptaoussanis/nippy#78]
Hi Peter, 

It would be nice for people who have to interact with nippy serialized data from other languages. I just had to do this and even tho the sources are documented it would have been nicer to have a readable document (wiki page even) instead.

**Comment by ptaoussanis** [comment]
Hi Max,

To be honest, this is unlikely something I'm going to be able to do anytime soon. Just very, very busy these days - so trying to prioritise my time on open source stuff. Still have 6+ libs I've been trying to find the time to release, so trying to cut down on non-critical stuff, esp. if it means ongoing maintenance.

In this case, trying to maintain a wiki, etc. would be a fairly large commitment for something that I suspect few people would use. (Esp. since the format's more or less self-documenting in the code for folks that need that info).

Will definitely continue trying to keep the internal format docs clear, etc.!

Sorry I couldn't be of more help on this, just a case of trying to prioritise efforts.

Cheers :-)
