### ISSUE TITLE
frozen with 2.9.x thawing with 2.11.y

### ISSUE THREAD

**Issue by harold** [ptaoussanis/nippy#82]
I have some data that was frozen with version ~2.9.x and I am trying to thaw it with version ~2.11.y (x and y are approximately 1 and 0-RC1).

I encounter this error:
```
ExceptionInfo No reader provided for custom type with internal id: 112
```

Are these versions incompatible? Or is something else afoot?

Any hints in general about freezing and thawing with differing versions?

Thanks in advance for your insight.

**Comment by ptaoussanis** [comment]
Hi Harold,

Frozen data should always be forward compatible. You'll want to double check though that both environments (old+new) have the exact same Nippy `extend-thaw`, `extend-freeze` calls + the same Clojure readers configured (if any of those are being used).

If none of that's helpful and the data's not to big, you can send me `(seq <your-frozen-byte-array>)` so that I can check the type signatures for further ideas.

Good luck!

**Comment by harold** [comment]
I appreciate the quick reply, and I am glad that the data is expected to be forward compatible (my team has nippy'd quite a bit of data, ha!)

The `extend-`s and reader configuration I hadn't thought of... Unsure if we're using those. Thanks for the hints.

The data is small, but I don't have it here on my home machine. If I'm still stuck tomorrow I'll post it for you to check out.

Thanks again!

**Comment by harold** [comment]
Embarrassing: I confused my `lein deps :tree` outputs, and was in fact trying to thaw nippy data that had been frozen in the _newer_ version!

I am good to go. Thank you for all your tremendous work---we run your code a lot every day and, if I can say so myself, it's just great.

Warmly!

**Comment by ptaoussanis** [comment]
No problem at all, easy mistake to make - thanks for confirming that it's working.

Cheers!

**Comment by ptaoussanis** [comment]
Btw just improved the error message to help make cases like this easier to diagnose in future, so appreciate the report.

**Comment by harold** [comment]
Epic nice!
