### ISSUE TITLE
Is nippy serialization canonical?

### ISSUE THREAD

**Issue by lvh** [ptaoussanis/nippy#86]
Does `(= a b)` imply that `(= (freeze a) (freeze b))`? (This is an important property for some cryptographic applications.)

**Comment by lvh** [comment]
Sorry; the real property is a little bit stronger: is a serialization canonical? That seems to be trivially not true if you let people pick compressors; but assuming the compressor is fixed?

**Comment by ptaoussanis** [comment]
Hi there, Nippy unfortunately makes no promises on this since it's not a
primary objective and may be difficult to promise in general.

As an implementation detail, such equality should hold for most simple data
types.

If you have cryptographic requirements, would recommend using an
appropriate hash designed for the application.

**Comment by lvh** [comment]
Thanks! Not particularly disappointing -- I have experience with canonicalizing serializers, so I was expecting as much.
